##
## EPITECH PROJECT, 2024
## Makefile
## File description:
## Makefile
##

CC = gcc

all:
	@make -C objdump
	@make -C nm

re:
	@make re -C objdump
	@make re -C nm

clean:
	@make clean -C objdump
	@make clean -C nm

fclean:
	@make fclean -C objdump
	@make fclean -C nm
