#!/usr/bin/python3

import sys

def usage():
    print("USAGE")
    print("\t./105torus opt a0 a1 a2 a3 a4 n\n")
    print("DESCRIPTION")
    print("\topt\tmethod option:")
    print("\t\t\t1 for the bisection method")
    print("\t\t\t2 for Newton's method")
    print("\t\t\t3 for the secant method")
    print("\ta[0-4]\tcoefficients of the equation")
    print("\tn\t\tprecision (the application of the polynomial", end='')
    print(" to the solution should\n\t\t\tbe smaller than 10^-n)")

def bisection(a0, a1, a2, a3, a4, n):
    a = 0
    b = 1
    while (b - a) > (10 ** -n):
        c = (a + b) / 2
        if (a0 + a1 * c + a2 * c ** 2 + a3 * c ** 3 + a4 * c ** 4) * (a0 + a1 * a + a2 * a ** 2 + a3 * a ** 3 + a4 * a ** 4) < 0:
            b = c
        else:
            a = c
        if (b - a) < (10 ** -n):
            print(f"x = %.{n}f" % c)
        else:
            print(f"x = %.{n}g" % c)

def newton(a0, a1, a2, a3, a4, n):
    x = 0.5
    print(f"x = %.{n}g" % x)
    while abs(a0 + a1 * x + a2 * x ** 2 + a3 * x ** 3 + a4 * x ** 4) > (10 ** -n):
        x = x - (a0 + a1 * x + a2 * x ** 2 + a3 * x ** 3 + a4 * x ** 4) / (a1 + 2 * a2 * x + 3 * a3 * x ** 2 + 4 * a4 * x ** 3)
        if abs(a0 + a1 * x + a2 * x ** 2 + a3 * x ** 3 + a4 * x ** 4) < (10 ** -n):
            print(f"x = %.{n}f" % x)
        else:
            print(f"x = %.{n}g" % x)

def secant(a0, a1, a2, a3, a4, n):
    x0 = 0
    x1 = 1
    started = False
    while abs(a0 + a1 * x1 + a2 * x1 ** 2 + a3 * x1 ** 3 + a4 * x1 ** 4) > (10 ** -n):
        x2 = x1 - (a0 + a1 * x1 + a2 * x1 ** 2 + a3 * x1 ** 3 + a4 * x1 ** 4) * (x1 - x0) / ((a0 + a1 * x1 + a2 * x1 ** 2 + a3 * x1 ** 3 + a4 * x1 ** 4) - (a0 + a1 * x0 + a2 * x0 ** 2 + a3 * x0 ** 3 + a4 * x0 ** 4))
        x0 = x1
        x1 = x2
        if started:
            print(f"x = %.{n}f" % x2)
        else:
            print(f"x = %.{n}g" % x2)
            started = True

def main():
    if len(sys.argv) == 2 and sys.argv[1] == "-h":
        usage()
        return 0
    if len(sys.argv) != 8:
        usage()
        return 84
    if sys.argv[1] == "1":
        bisection(float(sys.argv[2]), float(sys.argv[3]), float(sys.argv[4]), float(sys.argv[5]), float(sys.argv[6]), int(sys.argv[7]))
    elif sys.argv[1] == "2":
        newton(float(sys.argv[2]), float(sys.argv[3]), float(sys.argv[4]), float(sys.argv[5]), float(sys.argv[6]), int(sys.argv[7]))
    elif sys.argv[1] == "3":
        secant(float(sys.argv[2]), float(sys.argv[3]), float(sys.argv[4]), float(sys.argv[5]), float(sys.argv[6]), int(sys.argv[7]))
    else:
        usage()
        return 84

if __name__ == "__main__":
    quit(main())
