##
## EPITECH PROJECT, 2022
## Makefile
## File description:
## Makefile at the root
##

all:
	$(MAKE) -C lib/my/ all
	$(MAKE) -C antman/ all
	$(MAKE) -C giantman/ all

clean:
	rm -rf antman/antman

fclean: clean
	$(MAKE) -C lib/my/ fclean
	$(MAKE) -C antman/ fclean
	$(MAKE) -C giantman/ fclean

re:
	$(MAKE) -C lib/my/ re
	$(MAKE) -C antman/ re
	$(MAKE) -C giantman/ re
