##
## EPITECH PROJECT, 2021
## makefile
## File description:
## Makefile
##

all :
	make -C ./solver/
	make -C ./generator/

generator:
	make -C ./generator/

solver:
	make -C ./solver/

fclean:
	make fclean -C ./generator/
	make fclean -C ./solver

re : fclean all