##
## EPITECH PROJECT, 2024
## Makefile
## File description:
## Makefile
##

SRC = main.py \

NAME = groundhog \

all: $(NAME)

$(NAME):
	cp $(SRC) $(NAME)
	chmod +x $(NAME)

clean:
	rm -f $(NAME)

fclean: clean

re: fclean all
