#!/usr/bin/python3

import sys

def print_help():
    print("USAGE")
    print("\t./106bombyx n [k | i0 i1]\n")
    print("DESCRIPTION")
    print("\tn\tnumber of first generation individuals")
    print("\tk\tgrowth rate from 1 to 4")
    print("\ti0\tinitial generation (included)")
    print("\ti1\tfinal generation (included)")

def check_syntax(args):
    try:
        args = list(map(float, args))
    except ValueError:
        return None
    for arg in args:
        if (type(arg) != float and type(arg) != int) or arg < 0:
            return None
    return args

def compute_crowd(args):
    n, k = args
    for i in range(1, 101):
        print(f"{i} {n:.2f}")
        n *= k * (1000 - n) / 1000

def compute_graph(lst):
    n, i0, i1 = lst
    b = n

    for k in range(100, 400):
        n = b
        for i in range(int(i1) - int(i0) + 1):
            while i < i0:
                n = (k / 100) * n * (1000 - n) / 1000
                i += 1
            if k == 100:
                n = b / 100
            print(f"{k / 100:.2f} {n:.2f}")

def main():
    if not (2 <= len(sys.argv) <= 4):
        sys.exit(84)
    if len(sys.argv) == 2 and sys.argv[1] == "-h":
        print_help()
    elif 3 <= len(sys.argv) <= 4:
        args = check_syntax(sys.argv[1:])
        if args:
            if len(args) == 2:
                compute_crowd(args)
            elif len(args) == 3:
                compute_graph(args)
        else:
            sys.exit(84)
    else:
        sys.exit(84)

if __name__ == "__main__":
    main()
