#!/usr/bin/python3

from sys import argv

def print_help():
    line = "line"
    try:
        doc = open("readme.usage", "r")
        while line:
            line = doc.readline()
            print(line, end='')
        doc.close()
    except:
        quit(84)
    quit(0)

def check_syntax(lst):
    for i in range(1, len(lst)):
        try:
            lst[i] = float(lst[i])
        except:
            return 0
    return lst

def compute_crowd(lst):
    n, k = lst

    for i in range(100):
        print(f"{i + 1} {n:.2f}")
        n *= k * (1000 - n) / 1000

def compute_graph(lst):
    n, i0, i1 = lst
    b = n

    for k in range(100, 400):
        for i in range(int(i1 - i0) + 1):
            while i < i0:
                n = (k / 100) * n * (1000 - n) / 1000
                i += 1
            if k == 100:
                n = b / 100
            print(f"{k/100:.2f} {n:.2f}")

def main():
    if len(argv) == 2 and argv[1] == "-h":
        print_help()
        quit(84)
    if not(2 < len(argv) <= 5):
        quit(84)
    if not check_syntax(argv):
        quit(84)
    if len(argv) == 3:
        compute_crowd(list(argv[1:]))
    else:
        compute_graph(list(argv[1:]))

if __name__ == "__main__":
    main()
