##
## EPITECH PROJECT, 2022
## Untitled (Workspace)
## File description:
## Makefile
##

MAKE_ASM = make
MAKE_CW = make

all:
	@ cd asm && $(MAKE_ASM)
	@ cd corewar && $(MAKE_CW)

clean:
	@ cd asm && $(MAKE_ASM) clean
	@ cd corewar && $(MAKE_CW) clean

fclean:
	@ cd asm && $(MAKE_ASM) fclean
	@ cd corewar && $(MAKE_CW) fclean

re:
	@ cd asm && $(MAKE_ASM) re
	@ cd corewar && $(MAKE_CW) re

debug:
	@ cd asm && $(MAKE_ASM) debug
	@ cd corewar && $(MAKE_CW) debug
