#!/usr/bin/env python3
import sys
import os
from generator.network_generator import NetworkGenerator

def usage():
    print("USAGE\n./my_torch_generator config_file_1 nb_1 [config_file_2 nb_2...]")

def main():
    if len(sys.argv) == 2 and (sys.argv[1] == "--help" or sys.argv[1] == "-h"):
        usage()
        return 0
    if len(sys.argv) < 3:
        usage()
        return 84

    generator = NetworkGenerator()

    for i in range(1, len(sys.argv), 2):
        config_file = sys.argv[i]
        num_networks = int(sys.argv[i + 1])

        for j in range(num_networks):
            network = generator.generate_from_config(config_file)
            output_file = f"{os.path.basename(config_file)[:-5]}_{j+1}.nn"
            generator.save_network(network, output_file)

if __name__ == "__main__":
    exit(main())
